name: geospatial_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.4
  - matplotlib=3.6.2
  - numpy=1.23.5
  - pandas=1.5.2
  - scikit-image
  - scikit-learn
  - scipy=1.10.0
  - seaborn=0.12.2
  - pip:
      - pytorch>=1.12.1
      - torch>=1.11.02.0.0
      - torchmetrics>=0.9.2
      - torchvision==0.18.1
      - imageio==2.36.1
      - segmentation-models-pytorch==0.3.2
